version: 1
formatters:
  simple:
    class: logging.Formatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  stream_handler:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    level: INFO
    formatter: simple
loggers:
  homework1:
    level: INFO
    handlers: [stream_handler]