input_train_data_path: "data/heart.csv"
input_test_data_path: "data/test_sample.csv"
output_model_path: "models/model.pkl"
output_preprocessor_path: "models/preprocessor.pkl"
metric_path: "models/metrics.json"
predictions_path: "data/predictions.csv"
logging_config: "configs/logging_conf.yml"
split_params:
  val_size: 0.2
  random_state: 3
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target: "target"
train_params:
  model_type: "LogisticRegression"
  penalty: "l2"
  inverse_regularization_strength: 1.0
  fit_intercept: True
  solver: "lbfgs"
  max_iter: 1300
  random_state: 111